services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
        POSTGRES_PASSWORD: "pwd"
        POSTGRES_USER: "user"
    volumes:
      - postgres_data:/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:






